[package]
name = "sanskrit_vowel_mathematical_waveform"
version = "0.1.0"
edition = "2021"

[dependencies]
apodize = "1.0.0"
byteorder = "1.5.0"
cpal = "0.16.0"
half = { version = "2.6.0", features = ["use-intrinsics"] }
nalgebra = "0.34.0"
ndarray = "0.16.1"
realfft = "3.5.0"
rustdct = "0.7.1"
