# =============================================
# == Dhvani Project Master Configuration File ==
# =============================================
# This file contains shared settings and model-specific parameters.
# The model to run is now chosen via the `--model-type` command-line flag.

# --- Audio Feature Parameters (shared by all models) ---
[features]
sample_rate = 16000
frame_length_samples = 400 # 25ms
hop_length_samples = 160   # 10ms
n_fft = 512

# =============================================
# == Model-Specific Settings ==
# =============================================

# --- Settings for the GMM (Gaussian Mixture Model) ---
[gmm_settings]
# These parameters are only used when you run with --model-type gmm
n_mfcc = 40
n_mfcc_used = 39        # Number of MFCCs (minus C0) to use for scoring
gmm_components = 50
pattern_size_kb = 10240

# --- Settings for the ONNX (PyTorch CNN) Model ---
[onnx_settings]
# These parameters are only used when you run with --model-type onnx
n_mels = 40      # Number of Mel bands for the spectrogram (must match training)
input_width = 70 # The fixed width (time steps) of the model's input tensor
