
import os
import concurrent.futures
from typing import List, Callable, Any, Tuple, Optional
from .config import tqdm, HAS_TQDM

def process_batch_parallel(
    items: List[Any],
    process_func: Callable[[Any], Any],
    output_dir: str,
    output_ext: str = ".csv", # Extension to check for existence
    max_workers: int = None,
    description: str = "Processing"
) -> List[Any]:
    """
    Process a list of items in parallel using ProcessPoolExecutor.
    
    Args:
        items: List of items to process (usually file paths)
        process_func: Function that takes an item and returns a result
        output_dir: Directory where results are saved (used for skipping)
        output_ext: File extension of the expected output (to check for existence)
        max_workers: Number of parallel workers (default: CPU count)
        description: Description for the progress bar
        
    Returns:
        List of results (excluding None/failures)
    """
    if max_workers is None:
        max_workers = os.cpu_count() or 4
        
    results = []
    
    # We can't easily check for existence here without knowing the exact output filename 
    # generated by process_func. So we'll rely on process_func to handle skipping 
    # OR we can assume a convention if items are paths.
    # For now, we will let process_func handle the logic, but we provide the parallel wrapper.
    
    with concurrent.futures.ProcessPoolExecutor(max_workers=max_workers) as executor:
        # Submit all tasks
        future_to_item = {executor.submit(process_func, item): item for item in items}
        
        # Process as they complete
        if HAS_TQDM:
            with tqdm(total=len(items), desc=description) as pbar:
                for future in concurrent.futures.as_completed(future_to_item):
                    try:
                        res = future.result()
                        if res is not None:
                            results.append(res)
                    except Exception as e:
                        item = future_to_item[future]
                        print(f"Error processing {item}: {e}")
                    pbar.update(1)
        else:
            for future in concurrent.futures.as_completed(future_to_item):
                try:
                    res = future.result()
                    if res is not None:
                        results.append(res)
                except Exception as e:
                    item = future_to_item[future]
                    print(f"Error processing {item}: {e}")
                    
    return results
